{
 "title": "twitch-irc-rs",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "machine_instance", "query": { "query": "label_values(instance)" } },
   { "name": "machine_job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up/Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Joined Channels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "twitchirc_channels{job=\"$job\",instance=\"$instance\",type=\"server\"}"
    }
   ]
  },
  {
   "title": "Joined Ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitchirc_channels{instance=\"$instance\",job=\"$job\",type=\"server\"} / ignoring(type) twitchirc_channels{instance=\"$instance\",job=\"$job\",type=\"wanted\"}"
    }
   ]
  },
  {
   "title": "Incoming messages (PRIVMSG)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(twitchirc_messages_received{instance=\"$instance\",job=\"$job\",command=\"PRIVMSG\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Connections (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(twitchirc_connections{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Connections connected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitchirc_connections{instance=\"$instance\",job=\"$job\",state=\"open\"} / ignoring(instance, job, state) sum(twitchirc_connections{instance=\"$instance\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Wanted Channels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "twitchirc_channels{job=\"$job\",instance=\"$instance\",type=\"wanted\"}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Messages received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(twitchirc_messages_received{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "sum(rate(twitchirc_messages_received{instance=\"$instance\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "all commands"
    }
   ]
  },
  {
   "title": "Messages sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(twitchirc_messages_sent{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{command}}"
    },
    {
     "expr": "sum(rate(twitchirc_messages_sent{instance=\"$instance\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "all commands"
    }
   ]
  },
  { "title": "Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "twitchirc_channels{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Channels (zoom)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "twitchirc_channels{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "twitchirc_connections{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connection failures (20 minute blocks)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(increase(twitchirc_connections_failed{instance=\"$instance\",job=\"$job\"}[20m]))",
     "legendFormat": "Failed connections"
    }
   ]
  },
  { "title": "Process/Host Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Process CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "System"
    },
    {
     "expr": "rate(process_cpu_user_seconds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval]) + rate(process_cpu_system_seconds_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Process resident memory bytes"
    }
   ]
  },
  {
   "title": "Whole-host CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='guest',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval]))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Disk Busy on Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$machine_instance\",job=\"$machine_job\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}