name: Audit Rust dependencies

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *' # At 3:30 every day

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate lockfile # https://github.com/rustsec/audit-check/issues/27
        run: cargo generate-lockfile
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
